<?php

namespace proeflesBundle\Repository;

/**
 * deltaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class deltaRepository extends \Doctrine\ORM\EntityRepository
{
}
